(()=>{
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)||0);
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
let products=load('cc-products',window.CC_PRODUCTS),favorites=load('cc-favorites',[]),compare=load('cc-compare',[]),bought=load('cc-bought',[]),budget=load('cc-budget',12000),category='todos',query='',sort='priority';
const save=()=>{localStorage.setItem('cc-products',JSON.stringify(products));localStorage.setItem('cc-favorites',JSON.stringify(favorites));localStorage.setItem('cc-compare',JSON.stringify(compare));localStorage.setItem('cc-bought',JSON.stringify(bought));localStorage.setItem('cc-budget',JSON.stringify(budget));};
const best=p=>Math.min(...p.offers.map(o=>Number(o.cash)||Infinity));
const bestOffer=p=>p.offers.find(o=>Number(o.cash)===best(p));
const discount=p=>Math.round(((p.target-best(p))/p.target)*100);
const priorityValue=p=>({Alta:0,'Média':1,Baixa:2}[p.priority]??3);
function updateSummary(){const spent=products.filter(p=>bought.includes(p.id)).reduce((s,p)=>s+best(p),0);document.querySelector('#summaryItems').textContent=products.length;document.querySelector('#summaryBought').textContent=bought.length;document.querySelector('#summaryDeals').textContent=products.filter(p=>best(p)<=p.target).length;document.querySelector('#favoriteCount').textContent=favorites.length;document.querySelector('#compareCount').textContent=compare.length;document.querySelector('#budgetSummary').textContent=`${money(spent)} usados de ${money(budget)}`;document.querySelector('#budgetProgress').style.width=`${Math.min(100,spent/budget*100)}%`;}
function categories(){document.querySelector('#categoryBar').innerHTML=window.CC_CATEGORIES.map(([id,n])=>`<button class="${category===id?'active':''}" data-category="${id}">${n}</button>`).join('');}
function filtered(){let list=products.filter(p=>(category==='todos'||p.category===category)&&`${p.name} ${p.subtitle} ${p.features.join(' ')}`.toLowerCase().includes(query.toLowerCase()));if(sort==='price')list.sort((a,b)=>best(a)-best(b));else if(sort==='discount')list.sort((a,b)=>discount(b)-discount(a));else if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));else list.sort((a,b)=>priorityValue(a)-priorityValue(b));return list;}
function card(p){const b=best(p),ok=b<=p.target,status=ok?(discount(p)>=10?'Excelente':'Bom preço'):'Aguardar';return `<article class="product-card ${bought.includes(p.id)?'bought':''}"><div class="card-top"><span class="pill">${p.priority}</span><button class="favorite ${favorites.includes(p.id)?'active':''}" data-fav="${p.id}" title="Favoritar">♥</button></div><div class="product-visual" data-open="${p.id}">${p.emoji}</div><div class="card-body"><small>${window.CC_CATEGORIES.find(x=>x[0]===p.category)?.[1]||''}</small><h3>${p.name}</h3><p>${p.subtitle}</p><div class="price-label">Melhor preço cadastrado</div><div class="price">${money(b)}</div><div class="target">Alvo: ${money(p.target)} · ${bestOffer(p)?.store||''}</div><span class="status ${ok?'':'wait'}">${status}</span><div class="card-actions"><button class="${compare.includes(p.id)?'active':''}" data-compare="${p.id}">${compare.includes(p.id)?'Comparando':'Comparar'}</button><button class="${bought.includes(p.id)?'active':''}" data-bought="${p.id}">${bought.includes(p.id)?'Comprado':'Marcar compra'}</button></div><div class="wide-actions"><button class="button secondary" data-open="${p.id}">Ver e editar preços</button></div></div></article>`;}
function renderCatalog(){categories();const list=filtered();document.querySelector('#resultCount').textContent=`${list.length} produtos encontrados`;document.querySelector('#productGrid').innerHTML=list.map(card).join('')||'<div class="empty">Nenhum produto encontrado.</div>';updateSummary();}
function showView(name){document.querySelectorAll('.section-view').forEach(x=>x.classList.remove('active'));const id={catalog:'catalogView',compare:'compareView',planning:'planningView',favorites:'favoritesView'}[name];document.querySelector('#'+id).classList.add('active');if(name==='compare')renderCompare();if(name==='planning')renderPlanning();if(name==='favorites')renderFavorites();window.scrollTo({top:0,behavior:'smooth'});}
function renderCompare(){const ps=products.filter(p=>compare.includes(p.id));const el=document.querySelector('#compareView');if(!ps.length){el.innerHTML='<div class="empty"><h2>Nenhum produto selecionado</h2><p>Escolha até quatro itens no catálogo para comparar.</p><button class="button primary" data-view="catalog">Ir ao catálogo</button></div>';return;}const rows=[['Produto',p=>`${p.emoji} ${p.name}`],['Melhor preço',p=>money(best(p))],['Preço alvo',p=>money(p.target)],['Prioridade',p=>p.priority],['Características',p=>p.features.join(', ')],['Melhor loja',p=>bestOffer(p)?.store||'']];el.innerHTML=`<div class="view-title"><span class="overline">COMPARADOR</span><h2>Comparação lado a lado</h2><p>Até quatro produtos selecionados.</p></div><div class="compare-wrap"><table class="compare-table">${rows.map(([n,fn])=>`<tr><th>${n}</th>${ps.map(p=>`<td>${fn(p)}${n==='Produto'?`<br><button class="button secondary" data-remove-compare="${p.id}">Remover</button>`:''}</td>`).join('')}</tr>`).join('')}</table></div>`;}
function renderPlanning(){const spent=products.filter(p=>bought.includes(p.id)).reduce((s,p)=>s+best(p),0),remaining=budget-spent;document.querySelector('#planningView').innerHTML=`<div class="view-title"><span class="overline">PLANEJAMENTO</span><h2>Orçamento da casa</h2><p>Acompanhem o que já foi comprado e o que ainda falta.</p></div><div class="planning-grid"><div class="metric"><small>Orçamento total</small><strong>${money(budget)}</strong><input id="budgetInput" type="number" value="${budget}"></div><div class="metric"><small>Total comprado</small><strong>${money(spent)}</strong></div><div class="metric"><small>Saldo restante</small><strong>${money(remaining)}</strong></div><div class="metric"><small>Itens comprados</small><strong>${bought.length}/${products.length}</strong></div></div><div class="checklist">${products.map(p=>`<div class="check-row"><input type="checkbox" data-bought="${p.id}" ${bought.includes(p.id)?'checked':''}><div><strong>${p.emoji} ${p.name}</strong><small>${bestOffer(p)?.store||''}</small></div><strong>${money(best(p))}</strong><span class="priority-text pill">${p.priority}</span></div>`).join('')}</div>`;}
function renderFavorites(){const ps=products.filter(p=>favorites.includes(p.id));document.querySelector('#favoritesView').innerHTML=`<div class="view-title"><span class="overline">FAVORITOS</span><h2>Itens salvos</h2><p>Produtos que vocês querem acompanhar de perto.</p></div>${ps.length?`<div class="product-grid">${ps.map(card).join('')}</div>`:'<div class="empty"><h2>Nenhum favorito</h2><p>Use o coração nos produtos para salvá-los aqui.</p><button class="button primary" data-view="catalog">Ir ao catálogo</button></div>'}`;}
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;document.querySelector('#dialogContent').innerHTML=`<div class="dialog-head"><div class="dialog-emoji">${p.emoji}</div><div><span class="overline">EDITAR PRODUTO</span><h2>${p.name}</h2><p>${p.subtitle}</p></div></div><div class="form-grid"><label>Preço alvo<input id="editTarget" type="number" value="${p.target}"></label><label>Prioridade<select id="editPriority"><option ${p.priority==='Alta'?'selected':''}>Alta</option><option ${p.priority==='Média'?'selected':''}>Média</option><option ${p.priority==='Baixa'?'selected':''}>Baixa</option></select></label></div><h3>Ofertas cadastradas</h3><div id="offerEditor">${p.offers.map((o,i)=>`<div class="offer-row"><label>Loja<input data-offer-store="${i}" type="text" value="${o.store}"></label><label>À vista<input data-offer-cash="${i}" type="number" value="${o.cash}"></label><label>Parcelado<input data-offer-installments="${i}" type="number" value="${o.installments}"></label></div>`).join('')}</div><div class="dialog-actions"><button class="button secondary" value="cancel">Cancelar</button><button class="button primary" type="button" data-save-product="${p.id}">Salvar alterações</button></div>`;document.querySelector('#productDialog').showModal();}
function saveProduct(id){const p=products.find(x=>x.id===id);p.target=Number(document.querySelector('#editTarget').value)||0;p.priority=document.querySelector('#editPriority').value;p.offers=p.offers.map((o,i)=>({store:document.querySelector(`[data-offer-store="${i}"]`).value,cash:Number(document.querySelector(`[data-offer-cash="${i}"]`).value)||0,installments:Number(document.querySelector(`[data-offer-installments="${i}"]`).value)||0}));save();document.querySelector('#productDialog').close();renderCatalog();}
document.addEventListener('click',e=>{const t=e.target.closest('button,a,.product-visual');if(!t)return;if(t.dataset.category){category=t.dataset.category;renderCatalog()}if(t.dataset.fav){favorites=favorites.includes(t.dataset.fav)?favorites.filter(x=>x!==t.dataset.fav):[...favorites,t.dataset.fav];save();renderCatalog();if(document.querySelector('#favoritesView').classList.contains('active'))renderFavorites()}if(t.dataset.compare){compare=compare.includes(t.dataset.compare)?compare.filter(x=>x!==t.dataset.compare):compare.length>=4?[...compare.slice(1),t.dataset.compare]:[...compare,t.dataset.compare];save();renderCatalog()}if(t.dataset.bought){bought=bought.includes(t.dataset.bought)?bought.filter(x=>x!==t.dataset.bought):[...bought,t.dataset.bought];save();renderCatalog();if(document.querySelector('#planningView').classList.contains('active'))renderPlanning()}if(t.dataset.open)openProduct(t.dataset.open);if(t.dataset.saveProduct)saveProduct(t.dataset.saveProduct);if(t.dataset.removeCompare){compare=compare.filter(x=>x!==t.dataset.removeCompare);save();renderCompare();updateSummary()}if(t.dataset.view)showView(t.dataset.view);});
document.querySelector('#searchInput').addEventListener('input',e=>{query=e.target.value;renderCatalog()});document.querySelector('#sortSelect').addEventListener('change',e=>{sort=e.target.value;renderCatalog()});document.querySelector('#menuButton').onclick=()=>document.querySelector('#mainNav').classList.toggle('open');document.querySelector('#themeButton').onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('cc-theme',next)};document.addEventListener('change',e=>{if(e.target.id==='budgetInput'){budget=Number(e.target.value)||0;save();renderPlanning();updateSummary()}});document.documentElement.dataset.theme=localStorage.getItem('cc-theme')||'light';if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});renderCatalog();
})();
