
const K={products:"cc_products",budget:"cc_budget",theme:"cc_theme",bought:"cc_bought",favorites:"cc_favorites",compare:"cc_compare"};
let products=JSON.parse(localStorage.getItem(K.products)||"null")||structuredClone(DEFAULT_PRODUCTS),budget=Number(localStorage.getItem(K.budget)||12000),bought=new Set(JSON.parse(localStorage.getItem(K.bought)||"[]")),favorites=new Set(JSON.parse(localStorage.getItem(K.favorites)||"[]")),compare=new Set(JSON.parse(localStorage.getItem(K.compare)||"[]"));
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=v=>(Number(v)||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"}),byId=id=>products.find(p=>p.id===id);
function esc(v){return String(v||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function save(){localStorage.setItem(K.products,JSON.stringify(products));localStorage.setItem(K.bought,JSON.stringify([...bought]));localStorage.setItem(K.favorites,JSON.stringify([...favorites]));localStorage.setItem(K.compare,JSON.stringify([...compare]))}
function state(p){if(!p.price)return["Sem oferta",""];return p.price<=p.target?["Bom preço","good"]:["Acima do alvo","wait"]}
function nav(v){$$(".tab").forEach(b=>b.classList.toggle("active",b.dataset.view===v));$$(".view").forEach(s=>s.classList.toggle("active",s.id===v));scrollTo({top:0,behavior:"smooth"})}
$$(".tab").forEach(b=>b.onclick=()=>nav(b.dataset.view));$$("[data-go]").forEach(b=>b.onclick=()=>nav(b.dataset.go));
function cats(){let s=$("#categoryFilter").value;$("#categoryFilter").innerHTML='<option value="">Todas as categorias</option>'+DEFAULT_CATEGORIES.map(c=>`<option>${c}</option>`).join("");$("#categoryFilter").value=s;$("#productCategory").innerHTML=DEFAULT_CATEGORIES.map(c=>`<option>${c}</option>`).join("")}
function card(p){let [label,cls]=state(p),fav=favorites.has(p.id),cmp=compare.has(p.id);let auto=p.autoUpdated?`<div class="auto-note">Atualizado automaticamente${p.installments?` · ${esc(p.installments)}`:""}<span class="auto-source">Mercado Livre</span></div>`:"";return `<article class="product"><div class="product-top"><div class="product-icon">${p.icon||"📦"}</div><span class="badge ${cls}">${label}</span></div><div><h3>${esc(p.name)}</h3><div class="meta">${esc(p.brand||"Sem marca definida")} · ${esc(p.category)}</div></div><div class="price-row"><div><div class="price">${p.price?money(p.price):"A pesquisar"}</div><div class="target">Alvo: ${money(p.target)}</div>${auto}</div><div class="meta">${esc(p.store)}</div></div><div class="product-actions"><button class="small ${fav?"active":""}" data-a="fav" data-id="${p.id}">${fav?"★ Favorito":"☆ Favoritar"}</button><button class="small ${cmp?"active":""}" data-a="compare" data-id="${p.id}">${cmp?"✓ Comparando":"Comparar"}</button><button class="small" data-a="edit" data-id="${p.id}">Editar</button><button class="small ${bought.has(p.id)?"active":""}" data-a="bought" data-id="${p.id}">${bought.has(p.id)?"Comprado":"Marcar comprado"}</button>${p.link?`<a class="small link" href="${p.link}" target="_blank">Abrir oferta</a>`:""}<button class="small danger" data-a="delete" data-id="${p.id}">Excluir</button></div></article>`}
function bind(el){el.querySelectorAll("[data-a]").forEach(b=>b.onclick=()=>action(b.dataset.a,b.dataset.id))}
function action(a,id){if(a==="fav")favorites.has(id)?favorites.delete(id):favorites.add(id);if(a==="compare"){if(compare.has(id))compare.delete(id);else if(compare.size<4)compare.add(id);else return alert("Máximo de 4 produtos.")}if(a==="bought")bought.has(id)?bought.delete(id):bought.add(id);if(a==="edit")return openModal(byId(id));if(a==="delete"){if(!confirm("Excluir este produto?"))return;products=products.filter(p=>p.id!==id);bought.delete(id);favorites.delete(id);compare.delete(id)}save();render()}
function render(){cats();$("#statItems").textContent=products.length;$("#statBought").textContent=bought.size;$("#statDeals").textContent=products.filter(p=>p.price>0&&p.price<=p.target).length;
let pri=products.filter(p=>!bought.has(p.id)).sort((a,b)=>(a.priority||99)-(b.priority||99)).slice(0,6);$("#priorityGrid").innerHTML=pri.map(card).join("");bind($("#priorityGrid"));
$("#categorySummary").innerHTML=DEFAULT_CATEGORIES.map(c=>{let l=products.filter(p=>p.category===c);return `<div><span>${c}</span><strong>${l.filter(p=>bought.has(p.id)).length}/${l.length}</strong><small class="meta">comprados</small></div>`}).join("");renderProducts();renderCompare();renderChecklist();renderBudget()}
function renderProducts(){let q=$("#searchInput").value.toLowerCase(),c=$("#categoryFilter").value,s=$("#statusFilter").value,l=products.filter(p=>(!q||(p.name+" "+p.brand+" "+p.category).toLowerCase().includes(q))&&(!c||p.category===c)&&(!s||(s==="comprado"&&bought.has(p.id))||(s==="pendente"&&!bought.has(p.id))||(s==="favorito"&&favorites.has(p.id))));$("#productsGrid").innerHTML=l.length?l.map(card).join(""):'<div class="empty">Nenhum produto encontrado.</div>';bind($("#productsGrid"))}
["searchInput","categoryFilter","statusFilter"].forEach(id=>$("#"+id).addEventListener("input",renderProducts));
function renderCompare(){let l=[...compare].map(byId).filter(Boolean);$("#compareEmpty").style.display=l.length?"none":"block";$("#compareGrid").innerHTML=l.map(p=>`<div class="compare-card"><div class="product-icon">${p.icon}</div><h3 style="margin:12px 0">${esc(p.name)}</h3>${[["Marca",p.brand||"Não definida"],["Categoria",p.category],["Preço alvo",money(p.target)],["Melhor preço",p.price?money(p.price):"Não informado"],["Loja",p.store||"Não informada"],["Observações",p.notes||"Sem observações"]].map(x=>`<div class="compare-row"><span>${x[0]}</span><strong>${esc(x[1])}</strong></div>`).join("")}<button class="secondary" style="width:100%;margin-top:14px" data-r="${p.id}">Remover</button></div>`).join("");$$("[data-r]").forEach(b=>b.onclick=()=>{compare.delete(b.dataset.r);save();render()})}
function renderChecklist(){$("#checklistContent").innerHTML=DEFAULT_CATEGORIES.map(c=>{let l=products.filter(p=>p.category===c);return l.length?`<section class="check-group"><h3>${c}</h3>${l.map(p=>`<label class="check-item ${bought.has(p.id)?"done":""}"><input type="checkbox" data-check="${p.id}" ${bought.has(p.id)?"checked":""}><span class="check-name">${esc(p.name)}</span><span class="spacer"></span><span class="check-price">${money(p.price||p.target)}</span></label>`).join("")}</section>`:""}).join("");$$("[data-check]").forEach(c=>c.onchange=()=>{c.checked?bought.add(c.dataset.check):bought.delete(c.dataset.check);save();render()})}
$("#resetChecklistBtn").onclick=()=>{if(confirm("Desmarcar todos?")){bought.clear();save();render()}};
function renderBudget(){$("#budgetInput").value=budget;let spent=products.filter(p=>bought.has(p.id)).reduce((s,p)=>s+(p.price||p.target),0),planned=products.filter(p=>!bought.has(p.id)).reduce((s,p)=>s+(p.price||p.target),0),bal=budget-spent,pc=budget?Math.min(100,Math.round(spent/budget*100)):0;$("#budgetTotal").textContent=money(budget);$("#budgetSpent").textContent=money(spent);$("#budgetBalance").textContent=money(bal);$("#budgetPlanned").textContent=money(planned);$("#budgetPercent").textContent=pc+"%";$("#budgetBar").style.width=pc+"%";$("#budgetByCategory").innerHTML=DEFAULT_CATEGORIES.map(c=>`<div class="cat-budget"><span>${c}</span><strong>${money(products.filter(p=>p.category===c).reduce((s,p)=>s+(p.price||p.target),0))}</strong></div>`).join("")}
$("#saveBudgetBtn").onclick=()=>{budget=Number($("#budgetInput").value)||0;localStorage.setItem(K.budget,budget);renderBudget()};
function openModal(p=null){$("#modalTitle").textContent=p?"Editar produto":"Adicionar produto";$("#productId").value=p?.id||"";$("#productName").value=p?.name||"";$("#productBrand").value=p?.brand||"";$("#productCategory").value=p?.category||DEFAULT_CATEGORIES[0];$("#productTarget").value=p?.target||"";$("#productPrice").value=p?.price||"";$("#productStore").value=p?.store||"";$("#productLink").value=p?.link||"";$("#productNotes").value=p?.notes||"";$("#productModal").classList.remove("hidden")}
function closeModal(){$("#productModal").classList.add("hidden")}$("#addProductBtn").onclick=()=>openModal();$$(".close-modal").forEach(b=>b.onclick=closeModal);$("#productModal").onclick=e=>{if(e.target.id==="productModal")closeModal()};
$("#productForm").onsubmit=e=>{e.preventDefault();let id=$("#productId").value||"p"+Date.now(),d={id,name:$("#productName").value.trim(),brand:$("#productBrand").value.trim(),category:$("#productCategory").value,target:Number($("#productTarget").value)||0,price:Number($("#productPrice").value)||0,store:$("#productStore").value.trim(),link:$("#productLink").value.trim(),notes:$("#productNotes").value.trim(),priority:99,icon:"📦"},i=products.findIndex(p=>p.id===id);i>=0?products[i]={...products[i],...d}:products.push(d);save();closeModal();render()};
if(localStorage.getItem(K.theme)==="dark")document.body.classList.add("dark");$("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem(K.theme,document.body.classList.contains("dark")?"dark":"light")};
async function loadAutomaticOffers(){
  const status=$("#autoStatus");
  try{
    const r=await fetch(`./data/ofertas.json?t=${Date.now()}`,{cache:"no-store"});
    if(!r.ok)throw new Error(`HTTP ${r.status}`);
    const data=await r.json();
    let changed=false;
    Object.entries(data.products||{}).forEach(([id,o])=>{
      const p=byId(id);
      if(!p||!Number(o.price))return;
      p.price=Number(o.price);p.store=o.store||"Mercado Livre";p.link=o.link||p.link;p.installments=o.installments||"";p.autoUpdated=true;p.checkedAt=o.checkedAt||data.updatedAt;changed=true;
    });
    if(changed)save();
    if(data.updatedAt){
      const d=new Date(data.updatedAt);
      const erros=(data.errors||[]).length;
      status.className=`auto-status ${erros?"warn":"ok"}`;
      status.innerHTML=`<strong>Atualização automática:</strong> ${d.toLocaleString("pt-BR")}. ${data.offers?.length||0} oferta(s) compatível(is) encontrada(s) no Mercado Livre.${erros?` ${erros} consulta(s) tiveram falha temporária.`:""}`;
    }
  }catch(e){status.className="auto-status warn";status.innerHTML="<strong>Atualização automática:</strong> os dados ainda não foram gerados. Execute o workflow no GitHub Actions."}
  render();
}
if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));render();loadAutomaticOffers();
