window.CC_CATEGORIES=[['todos','Todos'],['sala','Sala'],['cozinha','Cozinha'],['lavanderia','Lavanderia'],['quarto','Quarto'],['banheiro','Banheiro'],['climatizacao','Climatização'],['escritorio','Escritório'],['utilidades','Utilidades'],['seguranca','Segurança']];
const O=(store,cash,installments)=>({store,cash,installments});
window.CC_PRODUCTS=[
['tv','sala','📺','Smart TV 55” QLED','TCL, Samsung ou LG, 4K, boa imagem','Alta',2500,['55 polegadas','QLED ou superior','4K','10x sem juros'],[O('Mercado Livre',2469,2599),O('Amazon',2599,2699),O('Magazine Luiza',2649,2799)]],
['sofa','sala','🛋️','Sofá retrátil e reclinável','3 lugares, confortável e resistente','Média',1800,['3 lugares','Retrátil','Reclinável','Espuma D28'],[O('Mobly',1699,1799),O('MadeiraMadeira',1749,1899)]],
['rack','sala','🪵','Rack ou painel para TV','Para TV de 55”, com passa fios','Média',650,['Até 65”','Nichos','Passa fios'],[O('Magazine Luiza',549,599),O('Mercado Livre',579,629)]],
['mesa','sala','🍽️','Mesa de jantar com 4 cadeiras','Compacta e fácil de limpar','Baixa',1200,['4 lugares','Cadeiras estofadas'],[O('Casas Bahia',1099,1199),O('MadeiraMadeira',1149,1249)]],
['microondas','cozinha','♨️','Micro-ondas Electrolux ME23S 23L','Prata, 127V, linha Efficient','Alta',520,['23 litros','Prata','127V'],[O('Casas Bahia',559,599),O('Amazon',579,629)]],
['geladeira','cozinha','🧊','Geladeira Frost Free','Duplex, 375 a 450 litros e econômica','Alta',3200,['Frost Free','Inverter','Duplex','Selo A'],[O('Fast Shop',3099,3299),O('Magazine Luiza',3199,3399)]],
['fogao','cozinha','🔥','Fogão 5 bocas','Acendimento automático e forno amplo','Alta',1300,['5 bocas','Forno amplo'],[O('Casas Bahia',1199,1299),O('Ponto',1249,1349)]],
['airfryer','cozinha','🍟','Air fryer 5 a 7 litros','Cesto grande e boa potência','Média',500,['5L ou mais','1700W ou mais'],[O('Amazon',399,449),O('Mercado Livre',429,479)]],
['liquidificador','cozinha','🥤','Liquidificador potente','Jarra grande e lâminas resistentes','Média',250,['1000W ou mais','Jarra 2L+'],[O('Amazon',199,229),O('Magazine Luiza',219,249)]],
['cafeteira','cozinha','☕','Cafeteira elétrica','Para o café do dia a dia','Baixa',180,['Corta pingos','Placa aquecedora'],[O('Amazon',139,159),O('Mercado Livre',149,169)]],
['purificador','cozinha','💧','Purificador de água','Água natural e gelada','Média',800,['Água gelada','Refil acessível'],[O('Leroy Merlin',749,799),O('Amazon',779,829)]],
['panelas','cozinha','🍳','Jogo de panelas','Antiaderente ou inox, conjunto completo','Média',600,['5 peças ou mais','Tampas de vidro'],[O('Amazon',449,499),O('Mercado Livre',479,529)]],
['talheres','cozinha','🍴','Faqueiro completo','Uso diário e visitas','Baixa',250,['24 peças ou mais','Inox'],[O('Amazon',179,209),O('Mercado Livre',199,229)]],
['loucas','cozinha','🥣','Aparelho de jantar','Pratos, xícaras e tigelas','Baixa',450,['20 peças ou mais','Porcelana ou cerâmica'],[O('Amazon',349,399),O('Magazine Luiza',379,429)]],
['lavadora','lavanderia','🧺','Midea Wave Agitador 13kg','Automática, cesto inox, branca','Alta',1500,['13 kg','Cesto inox','10x sem juros'],[O('Mercado Livre',1429,1499),O('Magazine Luiza',1499,1599)]],
['varal','lavanderia','👕','Varal de chão com abas','Reforçado e dobrável','Média',180,['Aço','Com abas'],[O('Amazon',129,149),O('Mercado Livre',139,159)]],
['ferro','lavanderia','♨️','Ferro a vapor','Base antiaderente e vapor vertical','Baixa',180,['Vapor vertical','Autolimpeza'],[O('Amazon',139,159),O('Magazine Luiza',149,169)]],
['aspirador','utilidades','🧹','Aspirador vertical 2 em 1','Leve, potente e fácil de guardar','Média',450,['2 em 1','Filtro lavável'],[O('Amazon',329,379),O('Mercado Livre',349,399)]],
['cama','quarto','🛏️','Cama box casal ou queen','Base firme e estrutura reforçada','Alta',1000,['Estrutura reforçada','Tecido resistente'],[O('MadeiraMadeira',799,899),O('Mobly',849,949)]],
['colchao','quarto','😴','Colchão casal ou queen','Conforto intermediário para o casal','Alta',1400,['D33 ou molas ensacadas','Garantia'],[O('Mercado Livre',1199,1299),O('Magazine Luiza',1299,1399)]],
['guarda-roupa','quarto','🚪','Guarda-roupa casal','6 portas, gavetas e bom espaço','Alta',1800,['6 portas','3 gavetas ou mais'],[O('MadeiraMadeira',1599,1749),O('Casas Bahia',1699,1799)]],
['cabeceira','quarto','🗄️','Mesas de cabeceira, par','Com gaveta e nicho','Baixa',400,['Par','Com gaveta'],[O('Mercado Livre',279,319),O('MadeiraMadeira',299,349)]],
['cortina','quarto','🪟','Cortinas blackout','Para quarto e sala','Média',300,['Blackout','Fácil lavagem'],[O('Amazon',179,219),O('Mercado Livre',199,239)]],
['roupa-cama','quarto','🛌','Kit roupa de cama','Lençóis, travesseiros e edredom','Média',600,['2 jogos de lençol','Edredom','Travesseiros'],[O('Amazon',469,529),O('Magazine Luiza',499,559)]],
['chuveiro','banheiro','🚿','Chuveiro eletrônico','Controle gradual de temperatura','Alta',350,['Eletrônico','Boa vazão'],[O('Leroy Merlin',269,299),O('Amazon',289,319)]],
['gabinete','banheiro','🪞','Gabinete com espelho','Compacto e resistente à umidade','Média',700,['Espelho','Gabinete'],[O('Leroy Merlin',599,649),O('MadeiraMadeira',629,699)]],
['toalhas','banheiro','🧻','Jogo de toalhas','Banho, rosto e piso','Média',300,['Algodão','Boa gramatura'],[O('Amazon',219,249),O('Magazine Luiza',239,279)]],
['ar','climatizacao','❄️','Ar-condicionado inverter','9.000 ou 12.000 BTU, econômico','Média',2300,['Inverter','Selo A','Gás R32'],[O('Fast Shop',2099,2249),O('Magazine Luiza',2199,2349)]],
['ventilador','climatizacao','🌀','Ventilador silencioso','Mesa ou coluna','Baixa',300,['Silencioso','3 velocidades'],[O('Amazon',229,259),O('Mercado Livre',249,279)]],
['mesa-escritorio','escritorio','🖥️','Mesa para escritório','Espaço para notebook e organização','Baixa',500,['Boa profundidade','Passa fios'],[O('Mercado Livre',369,419),O('MadeiraMadeira',399,449)]],
['cadeira','escritorio','🪑','Cadeira ergonômica','Apoio lombar e ajuste de altura','Média',800,['Ajuste de altura','Apoio lombar'],[O('Amazon',649,729),O('Mercado Livre',699,779)]],
['ferramentas','utilidades','🧰','Kit básico de ferramentas','Para manutenção da casa','Média',350,['Furadeira','Chaves','Alicate','Trena'],[O('Mercado Livre',279,319),O('Amazon',299,339)]],
['escada','utilidades','🪜','Escada doméstica','Alumínio, 4 a 6 degraus','Média',350,['Alumínio','Antiderrapante'],[O('Leroy Merlin',289,319),O('Mercado Livre',299,339)]],
['camera','seguranca','📷','Câmera Wi-Fi interna','Visão noturna e acesso pelo celular','Baixa',250,['Wi-Fi','Visão noturna','Áudio'],[O('Amazon',179,209),O('Mercado Livre',189,219)]],
['fechadura','seguranca','🔐','Fechadura digital','Senha e travamento automático','Baixa',700,['Senha','Travamento automático'],[O('Amazon',579,629),O('Mercado Livre',599,649)]]
.map(([id,category,emoji,name,subtitle,priority,target,features,offers])=>({id,category,emoji,name,subtitle,priority,target,features,offers}));
