create extension if not exists pgcrypto;

create table if not exists public.offers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  brand text,
  category text not null default 'Outros',
  store text not null,
  price numeric(12,2) not null check (price >= 0),
  old_price numeric(12,2),
  shipping_text text,
  installments text,
  image_url text,
  product_url text,
  affiliate_url text not null,
  rating numeric(2,1) default 4.7,
  reviews integer default 0,
  is_verified boolean not null default true,
  active boolean not null default true,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.affiliate_clicks (
  id bigint generated by default as identity primary key,
  offer_id uuid references public.offers(id) on delete set null,
  store text,
  referrer text,
  user_agent text,
  clicked_at timestamptz not null default now()
);

create or replace view public.offers_public as
select id,name,brand,category,store,price,old_price,shipping_text,installments,
image_url,product_url,affiliate_url,rating,reviews,is_verified,active,updated_at
from public.offers where active=true;

alter table public.offers enable row level security;
alter table public.affiliate_clicks enable row level security;

drop policy if exists "Leitura pública de ofertas" on public.offers;
create policy "Leitura pública de ofertas" on public.offers
for select to anon, authenticated using (active=true);

drop policy if exists "Registrar cliques públicos" on public.affiliate_clicks;
create policy "Registrar cliques públicos" on public.affiliate_clicks
for insert to anon, authenticated with check (true);

grant select on public.offers_public to anon, authenticated;
grant insert on public.affiliate_clicks to anon, authenticated;
grant usage, select on sequence public.affiliate_clicks_id_seq to anon, authenticated;
