create extension if not exists pgcrypto;

create table if not exists public.offers (
  id uuid primary key default gen_random_uuid(),
  external_id text,
  source text not null default 'manual',
  name text not null,
  brand text,
  category text not null default 'Outros',
  store text not null,
  price numeric(12,2) not null,
  old_price numeric(12,2),
  shipping_text text,
  installments text,
  quality text,
  rating numeric(3,2),
  reviews integer default 0,
  image_url text,
  product_url text not null,
  affiliate_url text,
  is_verified boolean default true,
  active boolean default true,
  flash boolean default false,
  updated_at timestamptz default now(),
  created_at timestamptz default now()
);

create table if not exists public.price_history (
  id bigint generated by default as identity primary key,
  offer_id uuid references public.offers(id) on delete cascade,
  price numeric(12,2) not null,
  captured_at timestamptz default now()
);

create table if not exists public.coupons (
  id uuid primary key default gen_random_uuid(),
  store text not null,
  code text not null,
  title text not null,
  description text,
  starts_at timestamptz default now(),
  expires_at timestamptz,
  active boolean default true,
  created_at timestamptz default now(),
  unique(store,code)
);

create table if not exists public.price_alerts (
  id uuid primary key default gen_random_uuid(),
  email text not null,
  query text not null,
  target_price numeric(12,2),
  stores text[],
  active boolean default true,
  created_at timestamptz default now()
);

alter table public.offers enable row level security;
alter table public.price_history enable row level security;
alter table public.coupons enable row level security;

create policy "public read offers" on public.offers for select to anon,authenticated using(active=true);
create policy "public read history" on public.price_history for select to anon,authenticated using(true);
create policy "public read coupons" on public.coupons for select to anon,authenticated using(active=true);
